#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging\|Unknown")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=5
FIRST_VALUE=25
SECOND_VALUE=60

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
    echo "${BATTERY_POWER}%+"
    echo "${BATTERY_POWER}%+"
    echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
    if [[ ${BATTERY_POWER} -le ${URGENT_VALUE} ]]; then
        echo "${BATTERY_POWER}%-"
        echo "${BATTERY_POWER}%-"
        echo ""
    elif [[ ${BATTERY_POWER} -le ${FIRST_VALUE} ]]; then
        echo "${BATTERY_POWER}%-"
        echo "${BATTERY_POWER}%-"
        echo ""
    elif [[ ${BATTERY_POWER} -le ${SECOND_VALUE} ]]; then
        echo "${BATTERY_POWER}%-"
        echo "${BATTERY_POWER}%-"
        echo ""
    else
        echo "${BATTERY_POWER}%-"
        echo "${BATTERY_POWER}%-"
        echo ""
    fi
else
  echo "${BATTERY_POWER}%"
  echo "${BATTERY_POWER}%"
  echo ""
fi
